apiVersion: v1
kind: Service
metadata:
  name: jsmidsem-service
spec:
  type: NodePort
  selector:
    app: jsmidsem
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30005
